# For more information: https://laravel.com/docs/sail
version: '3'
services:
    sail-8.1:
        build:
            context: ./runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
                WWWUSER: '${WWWUSER}'
        image: becagis/sail:8.1
